### ISSUE TITLE
Add Support For Bucketed Items

### ISSUE THREAD

**Issue by hunterwilliams** [ryanjdew/ml-highcharts-ng#2]
As a developer/user, I would like items to be able to be bucketed so they display together in a chart.

**Comment by janmichaelyu** [comment]
I've investigated this and this is already supported, right? Just add the bucketed constraint in the search options, use the constraint name in the graph options, and add the 'ml-search-controller' value in <ml-highchart highchart-config="ctrl.highchartConfig" ml-search="ctrl.mlSearch" ml-search-controller="ctrl"></ml-highchart>.

**Comment by ryanjdew** [comment]
Ah, yes. Closing this ticket. Thanks @janmichaelyu.

**Comment by janmichaelyu** [comment]
Needs a new compile/tag, I think.

**Comment by grtjn** [comment]
@janmichaelyu what do you mean?
