### ISSUE TITLE
Support for bubble charts

### ISSUE THREAD

**Issue by grtjn** [ryanjdew/ml-highcharts-ng#6]
The bubble chart takes a z-axis for the size of the bubbles. It could for instance be used to show co-occurrences together with their frequency (as size). Maybe even 'normalize' the frequencies.

It looked like z-axis wasn't supported yet at all. Could serve a purpose for other 3d chart types as well?

**Comment by ryanjdew** [comment]
Added support in PR #3

**Comment by grtjn** [comment]
Not clear from PR #3 if this was actually covered or not. @hunterwilliams can you tell?

**Comment by hunterwilliams** [comment]
It added support for filling in the z-axis. There may be use cases where it doesn't work well though.

**Comment by grtjn** [comment]
good enough for me, thnx..
